name: Setup Nix with cache
description: Install Nix and restore/save Nix store cache

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
    - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
      with:
        primary-key: nix-v1-${{ runner.os }}-${{ hashFiles('flake.lock') }}
        restore-prefixes-first-match: nix-v1-${{ runner.os }}-
        gc-max-store-size-linux: 5G
        purge: true
        purge-prefixes: nix-v1-${{ runner.os }}-
        purge-last-accessed: P7D
        purge-primary-key: never
