name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/setup-nix
      - name: Flake check
        shell: bash
        run: |
          eval "$(nix print-dev-env)"
          just check
      - name: Format check
        shell: bash
        run: |
          eval "$(nix print-dev-env)"
          just fmt-check
      - name: Build mo for current system
        shell: bash
        run: |
          eval "$(nix print-dev-env)"
          just build
